#!/bin/bash
set -e

source "$(dirname "$(realpath "$0")")"/functions.sh

install_apt_packages
install_pip_packages
install_ohmyzsh
install_neovim_extensions
install_standalone_clangd

# TODO: This breaks docker builds :)
install_fonts

DECRYPT=${DECRYPT:-no}
if [ $DECRYPT = yes ]; then
  yadm decrypt
else
  echo "Skipping encrypted files, as requested"
fi
