#!/bin/bash
set -e

source "$(dirname "$(realpath "$0")")"/functions.sh

print_intro "dotfile installation"

install_packages_apt
install_packages_pip
install_ohmyzsh
install_neovim
install_node
install_clangd
install_fonts


decrypt_files


print_success "Installation compleated"
