#!/bin/bash
set -e

source "$(dirname "$(realpath "$0")")"/functions.sh

print_intro "dotfile installation"

install_packages_apt
install_packages_pip
install_ohmyzsh
install_neovim
install_standalone_clangd
install_fonts

DECRYPT=${DECRYPT:-no}
if [ $DECRYPT = yes ]; then
  yadm decrypt
else
  echo "Skipping encrypted files, as requested"
fi
